/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  presets: [require("nativewind/preset")],
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed-dim": "#b9c7e0",
        "status-warning": "#9A3412",
        "on-secondary-fixed-variant": "#783200",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#c6c6cd",
        "on-tertiary-fixed": "#0d1c2f",
        "primary-container": "#131b2e",
        "surface-tint": "#565e74",
        "secondary-fixed": "#ffdbca",
        "surface-container": "#eceef0",
        "inverse-primary": "#bec6e0",
        "error-container": "#ffdad6",
        "rfly-blue": "#0F172A",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-surface": "#191c1e",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed": "#341100",
        "surface-slate": "#E2E8F0",
        "tertiary-fixed": "#d5e3fd",
        primary: "#000000",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#76859b",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#45464d",
        "status-success": "#166534",
        "secondary-fixed-dim": "#ffb690",
        "on-error": "#ffffff",
        "secondary-container": "#fd761a",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        outline: "#76777d",
        "on-secondary": "#ffffff",
        "tertiary-container": "#0d1c2f",
        surface: "#f7f9fb",
        tertiary: "#000000",
        "on-primary-fixed": "#131b2e",
        "on-primary-container": "#7c839b",
        background: "#f7f9fb",
        "inverse-surface": "#2d3133",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-container": "#5c2400",
        "status-offline": "#475569",
        "safety-orange": "#F97316",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed-variant": "#3a485c",
        "primary-fixed": "#dae2fd",
        secondary: "#9d4300",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-lg": "24px",
        "stack-md": "16px",
        gutter: "16px",
        "margin-mobile": "20px",
        "touch-target-min": "48px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "body-lg": ["IBM Plex Sans"],
        "headline-md": ["IBM Plex Sans"],
        "body-md": ["IBM Plex Sans"],
        "headline-lg": ["IBM Plex Sans"],
        "headline-lg-mobile": ["IBM Plex Sans"],
        "data-mono": ["JetBrains Mono"],
        "label-caps": ["IBM Plex Sans"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
