name: Operations Mobile Android Build

on:
  push:
    branches:
      - staging
    paths:
      - 'operations-mobile/**'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./operations-mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './operations-mobile/package.json'

      - name: Install dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Prebuild Android Project
        run: npx expo prebuild -p android --clean
        env:
          EXPO_PUBLIC_OC_API_URL: \${{ secrets.STAGING_API_URL }}

      - name: Build APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: operations-companion-release
          path: operations-mobile/android/app/build/outputs/apk/release/app-release.apk
